---

- name: Create a new database "lab"
  mysql_db:
    name: lab
    state: present

- name: add webuser user
  mysql_user:
    name: webuser
    password: Aa123456
    priv: 'lab.*:ALL'
    state: present

- name: copy sql script
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
  - { src: create_table.sql , dest: /var/tmp/create_table.sql }

- name: create table users and first entry
  mysql_db:
    name: lab
    state: import
    target: /var/tmp/create_table.sql
