---

- name: restart-haproxy
  service:
    name: haproxy 
    state: restarted

- name: save iptables
  command: service iptables save
  notify: iptables-restart

- name: iptables-restart
  service:
    name: iptables
    state: restarted
