---

- name: install epel repository
  yum: 
    name: epel-release
    state: present

- name: make sure iptables enabled and tsarted
  service:
    name: iptables
    state: started
    enabled: yes
